debug: true
secret_key: +s6cv712&nw4gsk)1dmgpje+f#%^4lhp@!up+=p3ts+hxz(fr2

allowed_hosts:
  - 127.0.0.1
  - ::1

installed_apps:
  - MainApp
  - FormApp
  - PictureApp

middleware:
  - xw::middleware::SecurityMiddleware
  - xw::middleware::CommonMiddleware
  - xw::middleware::XFrameOptionsMiddleware
  - xw::middleware::CookieMiddleware
  - UsefulMiddleware

logger:
  out:
    console: true

templates_env:
  directories:
    - templates
  use_app_directories: true
  auto_escape: true
  libraries:
    - MyLib

timezone:
  name: EET
  offset:
    hours: 3

static:
  root: static
  url: /static/

media:
  root: media
  url: /media/

data_upload_max_memory_size: 20971520
